pipeline {
    agent any

    environment {
        AWS_REGION = "us-west-1"  // Change to your AWS region
        S3_BUCKET = credentials('S3_BUCKET')  // Fetch S3 bucket from Jenkins credentials
        LAMBDA_FUNCTION_NAME = "etl_lambda"  // Lambda function name
    }

    stages {
        stage('Checkout Code') {
            steps {
                script {
                    git credentialsId: 'github-credentials', url: 'https://github.com/Nafeesp2001/demo-cloud.git', branch: 'main'
                }
            }
        }

        stage('Setup Environment') {
            steps {
                script {
                    sh 'pip install boto3 psycopg2-binary'
                }
            }
        }

        stage('Deploy Infrastructure with Terraform') {
            steps {
                script {
                    dir('terraform') {
                        sh '''
                        terraform init
                        terraform apply -auto-approve
                        '''
                    }
                }
            }
        }

        stage('Upload Sample Data to S3') {
            steps {
                script {
                    sh "aws s3 cp sample_data.json s3://${S3_BUCKET}/"
                }
            }
        }

        stage('Invoke AWS Lambda') {
            steps {
                script {
                    sh """
                    aws lambda invoke --function-name ${LAMBDA_FUNCTION_NAME} --payload '{}' response.json
                    cat response.json
                    """
                }
            }
        }

      
    }

    post {
        always {
            script {
                echo "Pipeline execution completed."
            }
        }
    }
}
